# Generated by Django 2.2.2 on 2019-07-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190731_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='trello_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
