# Generated by Django 2.2.2 on 2019-07-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_todoitem_trello_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='task_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
